<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="jest tests" tests="6" failures="2" errors="0" time="0.303">
  <testsuite name="undefined" errors="0" failures="2" skipped="0" timestamp="2023-11-13T08:45:07" time="0.216" tests="3">
    <testcase classname=" sum of a,b" name=" sum of a,b" time="0.002">
    </testcase>
    <testcase classname=" sum is " name=" sum is " time="0.006">
      <failure>Error: expect(received).toBe(expected) // Object.is equality

Expected: undefined
Received: 5
    at Object.toBe (/home/vrushabh/projects/copy1/ymltesting/precheckins/value.test.js:10:24)
    at Promise.then.completed (/home/vrushabh/projects/copy1/ymltesting/precheckins/node_modules/jest-circus/build/utils.js:298:28)
    at new Promise (&lt;anonymous&gt;)
    at callAsyncCircusFn (/home/vrushabh/projects/copy1/ymltesting/precheckins/node_modules/jest-circus/build/utils.js:231:10)
    at _callCircusTest (/home/vrushabh/projects/copy1/ymltesting/precheckins/node_modules/jest-circus/build/run.js:316:40)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at _runTest (/home/vrushabh/projects/copy1/ymltesting/precheckins/node_modules/jest-circus/build/run.js:252:3)
    at _runTestsForDescribeBlock (/home/vrushabh/projects/copy1/ymltesting/precheckins/node_modules/jest-circus/build/run.js:126:9)
    at run (/home/vrushabh/projects/copy1/ymltesting/precheckins/node_modules/jest-circus/build/run.js:71:3)
    at runAndTransformResultsToJestFormat (/home/vrushabh/projects/copy1/ymltesting/precheckins/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/home/vrushabh/projects/copy1/ymltesting/precheckins/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/home/vrushabh/projects/copy1/ymltesting/precheckins/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/home/vrushabh/projects/copy1/ymltesting/precheckins/node_modules/jest-runner/build/runTest.js:444:34)</failure>
    </testcase>
    <testcase classname=" fail" name=" fail" time="0">
      <failure>ReferenceError: val is not defined
    at Object.val (/home/vrushabh/projects/copy1/ymltesting/precheckins/value.test.js:14:24)
    at Promise.then.completed (/home/vrushabh/projects/copy1/ymltesting/precheckins/node_modules/jest-circus/build/utils.js:298:28)
    at new Promise (&lt;anonymous&gt;)
    at callAsyncCircusFn (/home/vrushabh/projects/copy1/ymltesting/precheckins/node_modules/jest-circus/build/utils.js:231:10)
    at _callCircusTest (/home/vrushabh/projects/copy1/ymltesting/precheckins/node_modules/jest-circus/build/run.js:316:40)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at _runTest (/home/vrushabh/projects/copy1/ymltesting/precheckins/node_modules/jest-circus/build/run.js:252:3)
    at _runTestsForDescribeBlock (/home/vrushabh/projects/copy1/ymltesting/precheckins/node_modules/jest-circus/build/run.js:126:9)
    at run (/home/vrushabh/projects/copy1/ymltesting/precheckins/node_modules/jest-circus/build/run.js:71:3)
    at runAndTransformResultsToJestFormat (/home/vrushabh/projects/copy1/ymltesting/precheckins/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/home/vrushabh/projects/copy1/ymltesting/precheckins/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/home/vrushabh/projects/copy1/ymltesting/precheckins/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/home/vrushabh/projects/copy1/ymltesting/precheckins/node_modules/jest-runner/build/runTest.js:444:34)</failure>
    </testcase>
  </testsuite>
  <testsuite name="undefined" errors="0" failures="0" skipped="0" timestamp="2023-11-13T08:45:07" time="0.042" tests="3">
    <testcase classname=" pass" name=" pass" time="0">
    </testcase>
    <testcase classname=" mult" name=" mult" time="0">
    </testcase>
    <testcase classname=" multiple" name=" multiple" time="0">
    </testcase>
  </testsuite>
</testsuites>